name: Setup action
description: Reusable action to setup node and install packages

runs:
  using: "composite"
  steps:

    - name: Install Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version: 24.11.0
        package-manager-cache: false

    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      name: Install pnpm
      with:
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: pnpm-store-${{ hashFiles('**/package.json') }}
        restore-keys: |
          pnpm-store-

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Cache turbo
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-
