import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  validationSidebar: [{ dirName: '.', type: 'autogenerated' }],
};

export default sidebars;
