import { ApiStyle } from '../../models/ApiStyle.js';

const CODE_FIRST_ADD_RESOURCE_SKILL_SOURCE: string = `---
name: add-resource
description: Add a complete persistence-backed HTTP resource to an app generated by @inversifyjs/create-http. Use for new entities, CRUD resources, or changes spanning Prisma, domain models, application ports, API models and controllers, and dependency injection. Do not use for an isolated endpoint tweak.
---

# Add a resource

Treat \`src/todo\`, \`src/app/scripts/initializeContainer.ts\`, \`src/app/scripts/bootstrap.ts\`, and \`prisma/schema.prisma\` as the working reference. Preserve the generated app's hexagonal boundaries and local naming conventions instead of introducing a second architecture.

## Establish the contract

Before editing, determine:

- fields, types, nullability, defaults, identifiers, and uniqueness
- relationships, cardinality, ownership, and delete behavior
- required HTTP operations, routes, pagination, filtering, and sorting
- authorization or tenancy rules, when relevant

Ask a focused question only when a missing choice would materially change the public API or data model. Otherwise state a conservative assumption and continue.

## Implement the vertical slice

1. Update \`prisma/schema.prisma\`. Create a new migration when a database-backed migration command is available. Never rewrite an existing migration and never invent migration SQL when the database is unavailable.
2. Add a domain model under \`src/<resource>/domain/models\`. Keep it independent of Prisma and HTTP concerns.
3. Define the persistence contract under \`application/ports\` and its service identifier under \`application/models\`.
4. Implement the Prisma adapter and a builder that maps Prisma records to the domain model. Keep database names such as \`created_at\` behind this boundary.
5. Add request and response API models with the OpenAPI 3.2 schema decorators used by the Todo resource. Do not expose generated Prisma types from the API.
6. Add a domain-to-API builder and controller. Use validated request decorators, explicit OpenAPI operation metadata, and the existing not-found response convention.
7. Add separate Inversify container modules for API bindings and Prisma persistence bindings.
8. Import and load both modules in \`src/app/scripts/initializeContainer.ts\`.
9. Add focused tests when the generated project already has a test setup. Do not introduce a new test framework solely for this resource unless requested.

## Preserve project conventions

- Keep \`.js\` extensions in TypeScript import specifiers.
- Prisma columns are snake_case (\`created_at\`, \`order_number\`, \`price_cents\`). Todo only uses single-word columns (\`title\`, \`completed\`); do not copy that as camelCase in Prisma (\`priceCents\`). Map snake_case columns to camelCase in the domain and API layers.
- Put owned child records in the same resource folder as the aggregate root.
- Match the Todo resource's pagination and soft-delete behavior when those features are requested.
- Use API builders to map domain values to versioned response models.
- Keep HTTP decorators and request models out of domain and application layers.
- Keep Prisma clients and generated Prisma types inside the Prisma adapter layer.
- For uWebSockets.js, mirror the existing controller's request-capture and JSON-header behavior for equivalent endpoint types.
- Use the Todo resource as a structural reference, but do not copy fields, routes, or operations that the new resource does not need.

## Validate

Format the changed files, regenerate the Prisma client, then run the project's build and lint commands. Run existing tests when present. Report the migration status and any validation that could not run, along with the concrete reason.
`;

const SCHEMA_FIRST_ADD_RESOURCE_SKILL_SOURCE: string = `---
name: add-resource
description: Add a complete persistence-backed HTTP resource to an app generated by @inversifyjs/create-http. Use for new entities, CRUD resources, or changes spanning Prisma, domain models, application ports, API JSON schemas and controllers, and dependency injection. Do not use for an isolated endpoint tweak.
---

# Add a resource

Treat \`src/todo\`, \`src/app/scripts/initializeContainer.ts\`, \`src/app/scripts/provideOpenApi.ts\`, \`src/app/scripts/generateApiTypes.ts\`, \`src/generated/api/index.ts\`, and \`prisma/schema.prisma\` as the working reference. Preserve the generated app's hexagonal boundaries and local naming conventions instead of introducing a second architecture.

This app is schema first. API models are JSON Schema objects registered on \`SwaggerUiProvider\`. TypeScript types are generated into \`src/generated/api\`. Do not add \`@OasSchema\` classes or call \`toSchema(Class)\`.

## Establish the contract

Before editing, determine:

- fields, types, nullability, defaults, identifiers, and uniqueness
- relationships, cardinality, ownership, and delete behavior
- required HTTP operations, routes, pagination, filtering, and sorting
- authorization or tenancy rules, when relevant

Ask a focused question only when a missing choice would materially change the public API or data model. Otherwise state a conservative assumption and continue.

## Implement the vertical slice

1. Update \`prisma/schema.prisma\`. Create a new migration when a database-backed migration command is available. Never rewrite an existing migration and never invent migration SQL when the database is unavailable.
2. Add a domain model under \`src/<resource>/domain/models\`. Keep it independent of Prisma and HTTP concerns.
3. Define the persistence contract under \`application/ports\` and its service identifier under \`application/models\`.
4. Implement the Prisma adapter and a builder that maps Prisma records to the domain model. Keep database names such as \`created_at\` behind this boundary.
5. Add request and response JSON schemas under \`src/<resource>/api/models\` (for example \`ProductSchemaV1.ts\` exporting \`productSchemaV1\`). Register each named schema on \`SwaggerUiProvider\` in \`src/app/scripts/provideOpenApi.ts\` as \`components.schemas.<Name>\`.
6. Before importing a new generated type, add \`export type <Name> = any;\` to \`src/generated/api/index.ts\`. Import those types from \`../../../generated/api/index.js\` in controllers and API builders. Document operations with \`$ref: '#/components/schemas/<Name>'\`. Map domain \`Date\` values to ISO strings in API builders because generated date-time fields are strings.
7. Add a controller that uses validated request decorators, explicit OpenAPI operation metadata, and the existing not-found response convention.
8. Add separate Inversify container modules for API bindings and Prisma persistence bindings.
9. Import and load both modules in \`src/app/scripts/initializeContainer.ts\`.
10. Add focused tests when the generated project already has a test setup. Do not introduce a new test framework solely for this resource unless requested.

## Preserve project conventions

- Keep \`.js\` extensions in TypeScript import specifiers.
- Prisma columns are snake_case (\`created_at\`, \`order_number\`, \`price_cents\`). Todo only uses single-word columns (\`title\`, \`completed\`); do not copy that as camelCase in Prisma (\`priceCents\`). Map snake_case columns to camelCase in the domain and API layers.
- Put owned child records in the same resource folder as the aggregate root.
- Match the Todo resource's pagination and soft-delete behavior when those features are requested.
- Use API builders to map domain values to generated response types.
- Keep HTTP decorators and request types out of domain and application layers.
- Keep Prisma clients and generated Prisma types inside the Prisma adapter layer.
- For uWebSockets.js, mirror the existing controller's request-capture and JSON-header behavior for equivalent endpoint types.
- Use the Todo resource as a structural reference, but do not copy fields, routes, or operations that the new resource does not need.
- Never leave a controller importing a generated type that is not yet stubbed as \`any\` or produced by \`generate:api\`.
- After adding schemas, run \`generate:api\` (or the project build) so stubs are replaced with real types.

## Validate

Format the changed files, regenerate the Prisma client, run \`generate:api\`, then run the project's build and lint commands. Run existing tests when present. Report the migration status and any validation that could not run, along with the concrete reason.
`;

export function generateAddResourceSkillSource(apiStyle: ApiStyle): string {
  if (apiStyle === ApiStyle.schemaFirst) {
    return SCHEMA_FIRST_ADD_RESOURCE_SKILL_SOURCE;
  }

  return CODE_FIRST_ADD_RESOURCE_SKILL_SOURCE;
}
